version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: techjam
            MYSQL_USER: root
            MYSQL_PASSWORD: passw0rd
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
        - "8000:8000"
        links:
        - mysql

volumes:
    mysql-data:
        driver: local
