# Generated by Django 2.2.11 on 2020-03-17 15:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tag',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10),
        ),
    ]
