# Generated by Django 3.0.4 on 2020-03-17 03:48

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('employee_id', models.CharField(max_length=255, verbose_name='社員id')),
                ('password', models.CharField(max_length=255, verbose_name='社員id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255, verbose_name='社員id')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('department', models.CharField(max_length=255, verbose_name='所属')),
                ('tag', django_mysql.models.JSONField(default=dict, verbose_name='タグ')),
                ('introduction', django_mysql.models.JSONField(default=dict, verbose_name='紹介文')),
                ('mail', models.EmailField(max_length=255, verbose_name='メール')),
                ('joined_at', models.CharField(max_length=255, verbose_name='入社年度')),
                ('created_by', models.CharField(max_length=255, verbose_name='作成者')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntroductionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='カテゴリーid')),
                ('category_name', models.CharField(max_length=255, verbose_name='カテゴリーの名前')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', django_mysql.models.JSONField(default=dict, verbose_name='タグ')),
                ('category', django_mysql.models.JSONField(default=dict, verbose_name='タグ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
