# Generated by Django 2.2.11 on 2020-03-18 05:39

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200318_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tag',
            field=django_mysql.models.JSONField(default=dict, verbose_name='タグ'),
        ),
    ]
