# Generated by Django 2.2.11 on 2020-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img_url',
            field=models.FileField(default='', upload_to='upload/'),
        ),
    ]
