# Generated by Django 2.2.11 on 2020-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200318_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='introduction',
        ),
        migrations.AddField(
            model_name='employee',
            name='introduction_1',
            field=models.CharField(default='', max_length=255, verbose_name='社歴'),
        ),
        migrations.AddField(
            model_name='employee',
            name='introduction_2',
            field=models.CharField(default='', max_length=255, verbose_name='アピール'),
        ),
        migrations.AddField(
            model_name='employee',
            name='introduction_3',
            field=models.CharField(default='', max_length=255, verbose_name='紹介'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag',
            field=models.CharField(default='', max_length=255, verbose_name='タグ'),
        ),
    ]
