# Generated by Django 2.2.11 on 2020-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200319_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='introduction_1_text',
            field=models.CharField(default='', max_length=255, verbose_name='社歴テキスト'),
        ),
        migrations.AddField(
            model_name='employee',
            name='introduction_2_text',
            field=models.CharField(default='', max_length=255, verbose_name='アピールテキスト'),
        ),
        migrations.AddField(
            model_name='employee',
            name='introduction_3_text',
            field=models.CharField(default='', max_length=255, verbose_name='紹介テキスト'),
        ),
    ]
