# Generated by Django 2.2.11 on 2020-03-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200319_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='introduction_1_text',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='introduction_2_text',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='introduction_3_text',
        ),
    ]
